"""
This script generates file(TARGET_FILE) that has website pages content mapped to variables. configure mappings inside FILES_TO_VARIABLES const
"""
TARGET_FILE = 'include/static_website_content.h'
DECLARATION_NAME = 'STATIC_WEBSITE_CONTENT_H'
FILES_TO_VARIABLES = {
    'page/index.html': 'INDEX_CONTENT',
    'page/scripts.js': 'SCRIPTS_CONTENT',
    'page/style.css': 'STYLE_CONTENT',
}

def generate_single_variable_declaration(variable_name: str, content: str):
    return f'const char {variable_name}[] PROGMEM = R"""(\n' + content + ')""";\n\n'

variables_declarations_section = ""
for file_name, variable_name in FILES_TO_VARIABLES.items():
    print(f'Mapping file {file_name} to variable {variable_name}')
    file = open(file_name, "r")
    file_content = file.read()
    variables_declarations_section += generate_single_variable_declaration(variable_name, file_content)


file = open(TARGET_FILE, "w")
file.write(f'''\
// AUTO-GENERATED ON BUILD
// DO NOT CHANGE
// generated by pre build script '../extra_script.py'
#include <avr/pgmspace.h>   

#ifndef {DECLARATION_NAME}
#define {DECLARATION_NAME}

{variables_declarations_section}
#endif // {DECLARATION_NAME}
''')
file.close()