"""
This script generates TARGET_FILE that has mapped files from SOURCE_FOLDER, which extensions are mapped in FILES_TYPE_TO_CONTENT_TYPE
"""
from subprocess import check_output
import os
import sys
import shutil

SOURCE_FOLDER = './page'
TARGET_FILE = 'include/handlers/static_website_content.h'
DECLARATION_NAME = 'STATIC_WEBSITE_CONTENT_H'
FILES_TYPE_TO_CONTENT_TYPE = {
    '.html': 'text/html',
    '.js': 'text/javascript',
    '.css': 'text/css',
}

minify_script_path = shutil.which("minify")
if (minify_script_path == None):
    print('\033[91mScript requires Minify node package\033[91m')
    print('\033[91mRef: npmjs.com/package/minify\033[91m')
    print('\033[91mInstall with: npm i minify -g\033[91m')
    exit(-1)

def generate_variable_declaration(variable_name: str, content: str):
    return f'const char {variable_name}[] PROGMEM = R"""({content})""";\n\n'

def generate_endpoint_declaration(endpoint: str, content_type: str, content_variable: str):
    return f'\tserver->on("/{endpoint}", HTTP_GET, [](AsyncWebServerRequest *request)\n\t\t\t  {{ request->send(200, "{content_type}", {content_variable}); }});\n\n'

def minify_file_and_read(file_path: str):
    minified_file = check_output([minify_script_path, file_path]).decode(sys.stdout.encoding).strip()
    print(f"Minify on {file_path} returned {len(minified_file)} chars")
    return minified_file

variables_declarations_section = ""
endpoints_declarations_section = ""

for file_name in os.listdir(SOURCE_FOLDER):
    variable_name, file_extension = os.path.splitext(file_name)
    file_path = os.path.join(SOURCE_FOLDER, file_name)

    if file_extension not in FILES_TYPE_TO_CONTENT_TYPE.keys():
        print(f'Skipped mapping file {file_name} ({file_extension}), it\'s extension is not on whitelist')
        continue

    variable_name = f'{variable_name}_content'.upper()
    print(f'Mapping file {file_name} to variable {variable_name}')

    file_content = minify_file_and_read(file_path)

    variables_declarations_section += generate_variable_declaration(variable_name, file_content)
    endpoints_declarations_section += generate_endpoint_declaration(file_name, FILES_TYPE_TO_CONTENT_TYPE[file_extension], variable_name)


file = open(TARGET_FILE, "w")
file.write(f'''\
// AUTO-GENERATED ON BUILD
// DO NOT CHANGE
// generated by pre build script '../extra_script.py'
#include <avr/pgmspace.h>
#include "ESPAsyncWebServer.h"

#ifndef {DECLARATION_NAME}
#define {DECLARATION_NAME}


{variables_declarations_section}
void init_static_content_endpoints(AsyncWebServer *server) {{
{endpoints_declarations_section}\
}}


#endif // {DECLARATION_NAME}
''')
file.close()